config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'leagues#index'

  resources :teams, only: :index

  resources :games, only: %i[index show update] do
    collection do
      get :replay
    end
  end

  resources :leagues, only: %i[index show]

  resources :schedules, only: %i[] do
    member do
      patch :postpone
    end
  end

  resources :team_traits, only: [] do
    member do
      get :increment, :decrement
    end
  end

  resources :stats, only: :index

  resources :play_sets, only: :index
  resources :off_def_charts, only: :index

  resources :offensive_play_sets, only: %i[create update]
  resources :defensive_play_sets, only: %i[create update]

  resources :miscs, only: :index
end

app/models/league.rb
class League < TeamGroup
  has_many :schedules, -> { order(:week, :number) },
                       foreign_key: 'team_group_id', dependent: :destroy
  has_many :playoff_berths, foreign_key: 'team_group_id', dependent: :destroy
  has_many :playoff_traits, foreign_key: 'team_group_id', dependent: :destroy

  def self.create_next
    last_league = League.order(:year).last
    ApplicationRecord.transaction do
      create!(
        name: last_league.name,
        year: last_league.year + 1,
        direct_teams: last_league.teams.map { |team|
          team.dup.tap { |new_team|
            new_team.update!(team_trait: team.team_trait.dup)
          }
        }
      )
    end
  end

  def prev_league
    self.class.find_by(year: year - 1)
  end

  def next_league
    self.class.find_by(year: year + 1)
  end

  def league
    self
  end

  def conferences
    child_groups
  end

  def divisions
    conferences.flat_map(&:divisions)
  end

  def games_finished
    @games_finished ||= schedules.includes(:game).where(is_playoff: false).map(&:game).find_all(&:final?)
  end

  def game_ongoing
    schedules.includes(:game).map(&:game).sort_by(&:updated_at).last.then { |game|
      game&.ongoing? ? game : nil
    }
  end

  def total_team_stats
    h_team_stats.values
  end

  def current_week
    next_schedule&.week
  end

  def next_schedule
    schedules.detect { |schedule| !schedule.game.final? }.tap do |schedule|

      return nil if conferences.empty?

      if schedules.size > 0 && schedule.nil?
        if playoff_berths.empty?
          berths = PlayoffBerth.build_initial_berths(self)
          PlayoffBerth.transaction do
            berths.map(&:save!)
          end
        else
          confirm_playoff_loser_elimination
        end

        playoff_schedules = PlayoffScheduleMaker.build_next_schedule_for(self)
        unless playoff_schedules.empty?
          Schedule.transaction do
            playoff_schedules.map(&:save!)
          end

          return next_schedule
        end
      end

    end
  end

  def postpone_next_schedule
    return unless next_schedule

    next_schedule.postpone
  end

  def next_week
    schedules.includes(:game).find_all { |schedule| schedule.game.final? }.pluck(:week).max + 1
  end

  def playoff_name_in(week)
    playoff_traits.find_by(week: week)&.name
  end

  def eliminate_loser_in!(game)
    return if !game.playoff? || !game.final?

    loser = game.loser
    playoff_berth = playoff_berths.find_by(team: loser)

    playoff_berth&.destroy
  end

  def to_s
    "#{year} #{abbr}"
  end

  private

    def h_team_stats
      @h_team_stats ||= make_h_team_stats
    end

    def make_h_team_stats
      h_init = teams.map { |team| [team.id, Stats::Team.new(team)] }.to_h
      games_finished.each_with_object(h_init) { |game, h|
        game_stats = Stats::Game.new(game)
        h[game.home_team.id].add(game_stats.stats_home    )
        h[game.visitors .id].add(game_stats.stats_visitors)
      }
    end

    def confirm_playoff_loser_elimination
      schedules.where(is_playoff: true).map(&:game).each do |game|
        eliminate_loser_in!(game)
      end
    end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    redirect_to League.order(:updated_at).last
  end

  def show
    @league = League.find(params[:id])

    @schedules_by_week = @league.schedules.includes(:game).regulars.group_by(&:week)
    @playoffs_by_week  = @league.schedules.includes(:game).playoffs.group_by(&:week)
    @game_played_last = @league.games_finished.sort_by(&:updated_at).last

    @displays_current_week = if params[:schedule_display]
                               params[:schedule_display] == 'current_week'
                             else
                               session[:displays_current_week]
                             end
    session[:displays_current_week] = @displays_current_week

    @shows_stats = params[:shows_stats] == 'true'
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper

  def team_result_display_for(team)
    team.team_record.to_s
  end

  def schedule_index_display(schedule, week)
    return week unless schedule
    content_tag :span do
      concat schedule.week
      concat content_tag :span, "-#{schedule.number}", class: 'number'
    end
  end

  def fgs_made_att_display(range, kick_stats)
    "#{kick_stats.fgs_made_from(range)}-#{kick_stats.attempts_from(range)}"
  end

  def link_to_toggle_stats
    label, params = @shows_stats ? ['Hide Stats', {}] \
                                 : ['Show Stats', {shows_stats: true}]
    link_to label, league_path(@league, params)
  end

  def schedule_with_team_result(schedule)
    return nil unless schedule
    game = schedule.game
    optional_strs = {}
    optional_strs['h'] = " (#{team_result_display_for(game.home_team)})"
    optional_strs['v'] = " (#{team_result_display_for(game.visitors )})"
    schedule.to_s(optional_strs)
  end
end

app/views/leagues/_playoffs.html.erb
<table class="playoffs">
  <% @playoffs_by_week.each do |week, schedules| -%>
    <tr>
      <td class="name" colspan="3"><%= @league.playoff_name_in(week) %></td>
    </tr>
    <% schedules.each do |schedule| -%>
      <% game = schedule.game -%>
      <tr>
        <td class="numeric <%= schedule && schedule == next_schedule ? 'next_game' : '' %>">
          <%= link_to_if game&.final?, schedule_index_display(schedule, week), game %>
        </td>
        <td><%= game %></td>
        <% if game.final? -%>
          <% score_winner, score_loser = game.result_and_scores_for(game.winner).last(2) -%>
          <td class="winner"><%= game.winner %></td>
          <td class="numeric"><%= score_winner %></td>
          <td class="centered">-</td>
          <td class><%= game.loser %></td>
          <td class="numeric"><%= score_loser %></td>
        <% end -%>
      </tr>
    <% end -%>
  <% end -%>
</table>

app/views/leagues/_schedules_by_week.html.erb
<table class="schedules_by_week">
  <caption><%= "Week #{week}" %></caption>

  <% schedules = @schedules_by_week[week]
     last_schedule = schedules.last -%>
  <% schedules.each do |schedule| -%>
    <% game = schedule.game -%>

    <tr>

      <%# TODO: Extract into partial %>
      <td class="numeric <%= schedule == next_schedule ? 'next_game' : '' %>">
        <%= link_to_if game&.final?, schedule_index_display(schedule, week), game %>
      </td>
      <% optional_strs = {}
         optional_strs['h'] = " (#{team_result_display_for(game.home_team)})"
         optional_strs['v'] = " (#{team_result_display_for(game.visitors )})" -%>
      <td><%= game ? game.to_s(optional_strs) : '(bye)' %></td>
      <% if game&.final? || game&.ongoing? -%>
        <% ongoing = game.ongoing? ? 'ongoing' : '' -%>
        <td class="numeric <%= ongoing %>"><%= game.score_visitors %></td>
        <td class="<%= ongoing %>">-</td>
        <td class="numeric <%= ongoing %>"><%= game.score_home %></td>
        <% if game.ongoing? -%>
          <td class="ongoing">
            <%= game_time_display(game) %>
          </td>
        <% elsif game.overtime? %>
          <td class="overtime_mark">OT</td>
        <% end -%>
      <% elsif schedule == next_schedule && schedule != last_schedule -%>
        <td colspan="4">
        <td><%= link_to 'Postpone', postpone_schedule_path(schedule, league_id: @league),
                method: :patch, id: 'link_to_postpone_schedule' %></td>
      <% end -%>

    </tr>
  <% end -%>
</table>

app/views/leagues/_standing.html.erb
<table class="standing">
  <thead>
    <th class="rank" hidden>
    <th>
    <th>G</th>
    <th>W</th>
    <th>L</th>
    <th>T</th>
    <th>PF</th>
    <th>PA</th>
    <th>Conference</th>
    <% unless @league.divisions.empty? -%>
      <th>Division</th>
    <% end -%>
    <th class="rank" hidden>
  </thead>
  <tbody>
    <% next_teams = @league.next_schedule&.game&.teams
       ongoing_teams = @league.game_ongoing&.teams -%>
    <% standing.each do |team_record| -%>
      <tr>
        <td class="rank" hidden><%= team_record.rank %></td>
        <% team = team_record.team
           classes = ['team', team.conference]
           classes << 'next_game' if next_teams&.include?(team)
           classes << 'ongoing' if ongoing_teams&.include?(team) -%>
        <td class="<%= classes.join(' ') %>"><%= team %></td>
        <td class="games  numeric"><%= team_record.games %></td>
        <td class="games  numeric"><%= team_record.won   %></td>
        <td class="games  numeric"><%= team_record.lost  %></td>
        <td class="games  numeric"><%= team_record.tied  %></td>
        <td class="points numeric"><%= team_record.pf    %></td>
        <td class="points numeric"><%= team_record.pa    %></td>
        <td class="centered"><%= team_record.conference %></td>
        <% unless @league.divisions.empty? -%>
          <td class="centered"><%= team_record.division %></td>
        <% end -%>
        <td class="rank" hidden><%= team_record.remark_display %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/leagues/_team_pass_stats.html.erb
<table class="stats">
  <thead>
    <tr>
      <th>
      <th>Att</th>
      <th>Cmp</th>
      <th>%Cmp</th>
      <th>Yards</th>
      <th>Y/Att</th>
      <th>Y/Cmp</th>
      <th>Long</th>
      <th>TD</th>
      <th>Int</th>
      <th>Sack</th>
      <th>FL</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% team_pass_stats.each do |pass_stats| -%>
      <tr>
        <td><%= pass_stats.owner %></td>
        <td class="numeric"><%= pass_stats.attempts %></td>
        <td class="numeric"><%= pass_stats.completions %></td>
        <td class="numeric"><%= "%3.1f" % pass_stats.pct_comp %></td>
        <td class="numeric"><%= pass_stats.yards.to_s(:delimited) %></td>
        <td class="numeric"><%= "%3.1f" % pass_stats.yards_per_attempt %></td>
        <td class="numeric"><%= "%3.1f" % pass_stats.yards_per_completion %></td>
        <td class="numeric"><%= pass_stats.long %></td>
        <td class="numeric"><%= pass_stats.touchdowns %></td>
        <td class="numeric"><%= pass_stats.intercepted %></td>
        <td class="numeric"><%= pass_stats.sacked %></td>
        <td class="numeric"><%= pass_stats.fumbles_lost %></td>
        <td class="numeric"><%= "%4.1f" % pass_stats.rating %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/leagues/_team_run_stats.html.erb
<table class="stats">
  <thead>
    <tr>
      <th>
      <th>Att</th>
      <th>Yards</th>
      <th>Avg</th>
      <th>Long</th>
      <th>TD</th>
      <th>FL</th>
    </tr>
  </thead>
  <tbody>
    <% team_run_stats.each do |run_stats| -%>
      <tr>
        <td><%= run_stats.owner %></td>
        <td class="numeric"><%= run_stats.attempts %></td>
        <td class="numeric"><%= run_stats.yards.to_s(:delimited) %></td>
        <td class="numeric"><%= "%3.1f" % run_stats.yards_per_carry %></td>
        <td class="numeric"><%= run_stats.long %></td>
        <td class="numeric"><%= run_stats.touchdowns %></td>
        <td class="numeric"><%= run_stats.fumbles_lost %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/leagues/_team_schedule.html.erb
<table class="team_schedule">
  <% next_teams = @league.next_schedule&.game&.teams
     ongoing_teams = @league.game_ongoing&.teams
     clazz = if next_teams&.include?(team)
               'next_game'
             elsif ongoing_teams&.include?(team)
               'ongoing'
             else
               ''
             end -%>
  <caption class="<%= clazz %>">
    <%= "#{team} (#{team_result_display_for(team)})" %>
  </caption>
  <% @schedules_by_week.each do |week, schedules| -%>
    <% schedule = schedules.detect { |s| s.for?(team) }
       game = schedule&.game
       game_display = game&.to_s&.sub(/\s*(?:at\s+)?#{team.name}\s*/, '') -%>
    <tr>
      <td class="numeric <%= schedule && schedule == next_schedule ? 'next_game' : '' %>">
        <%= link_to_if game&.final?, schedule_index_display(schedule, week), game %>
      </td>
      <td class="opponent"><%= game_display || '(bye)' %></td>
      <% if game&.final? -%>
        <% result, score_own, score_opp = game.result_and_scores_for(team) -%>
        <td class="result"><%= result %></td>
        <td class="numeric"><%= score_own %></td>
        <td>-</td>
        <td class="numeric"><%= score_opp %></td>
        <% if game&.overtime? %>
          <td class="overtime_mark">OT</td>
        <% end -%>
      <% end -%>
    </tr>
  <% end -%>
</table>

app/views/leagues/show.html.erb
<div class="leagues_show">
  <% next_schedule = @league.next_schedule -%>

  <div class="page_title">
    <%= @league %>

    <span id="toggle_schedule_display">
      <% next_value = @displays_current_week ? 'by_team' : 'current_week'
         label = next_value.camelize -%>
      <%= link_to label, league_path(@league, schedule_display: next_value) %>
    </span>

    <% prev_league, next_league = @league.prev_league, @league.next_league -%>
    <span><%= link_to_if prev_league, '<', prev_league %></span>
    <span><%= link_to_if next_league, '>', next_league %></span>

    <div class="actions">
      <%= link_to 'Team Traits', teams_path, target: '_blank' %>
      <%= link_to 'Play Sets', play_sets_path, target: '_blank' %>
      <%= link_to 'Off/Def Chart', off_def_charts_path, target: '_blank' %>
      <%= link_to 'Miscellaneous', miscs_path, target: '_blank' %>
    </div>
  </div>

  <% if @displays_current_week && @league.current_week -%>
    <div class="schedules_by_week">
      <%= render partial: 'schedules_by_week',
                 locals: {week: @league.current_week, next_schedule: next_schedule} %>
    </div>
  <% else -%>
    <% if !@league.direct_teams.empty? -%>
      <div class="team_schedules">
        <% @league.standing.teams.each do |team| -%>
          <%= render partial: 'team_schedule', locals: {team: team, next_schedule: next_schedule} %>
        <% end -%>
      </div>
    <% elsif @league.divisions.empty? -%>
      <% @league.conferences.each do |conference| -%>
        <div class="team_schedules">
          <% conference.standing.teams.each do |team| -%>
            <%= render partial: 'team_schedule', locals: {team: team, next_schedule: next_schedule} %>
          <% end -%>
        </div>
      <% end -%>
    <% else -%>
      <% @league.conferences.each do |conference| -%>
        <% conference.divisions.each do |division| -%>
          <div class="team_schedules">
            <% division.standing.teams.each do |team| -%>
              <%= render partial: 'team_schedule', locals: {team: team, next_schedule: next_schedule} %>
            <% end -%>
          </div>
        <% end -%>
      <% end -%>
    <% end -%>
  <% end -%>

  <div class="standing">
    <% if !@league.direct_teams.empty? -%>
      <%= render partial: 'standing', locals: {standing: @league.standing} %>
    <% elsif @league.divisions.empty? -%>
      <% @league.conferences.each do |conference| -%>
        <%= render partial: 'standing', locals: {standing: conference.standing} %>
      <% end -%>
    <% else -%>
      <div style="display: flex;">
        <% @league.conferences.each do |conference| -%>
          <div>
            <% conference.divisions.each do |division| -%>
              <%= render partial: 'standing', locals: {standing: division.standing} %>
            <% end -%>
          </div>
        <% end -%>
      </div>
    <% end -%>

    <div class="team_traits" hidden>
      <%= render partial: 'teams/traits', locals: {teams: @league.standing.teams} %>
    </div>
  </div>

  <% unless @playoffs_by_week.empty? -%>
    <div class="playoff_schedules">
      <%= render partial: 'playoffs', locals: {next_schedule: next_schedule} %>
    </div>
  <% end -%>

  <div class="links">
    <% if next_schedule && !next_schedule.game.ongoing? -%>
      <%= link_to "Next => #{schedule_with_team_result(next_schedule)}", next_schedule.game %>
    <% end -%>
    <%= link_to 'Games', games_path(league_id: @league) %>
    <%= link_to 'Teams', '#', id: 'toggle_teams' %>
    <%= link_to_toggle_stats %>
    <%= link_to 'Last Game', @game_played_last %>
    <% if game_ongoing = @league.game_ongoing -%>
      <%= link_to "Ongoing Game (#{live_score_display(game_ongoing)})", game_ongoing %>
    <% end -%>
  </div>

  <% if @shows_stats -%>
    <div class="stats_tables">
      <%= render partial: 'team_run_stats',
            locals: {team_run_stats: @league.total_team_stats.map(&:run_stats).sort_by { |s| -s.yards }} %>

      <%= render partial: 'team_pass_stats',
            locals: {team_pass_stats: @league.total_team_stats.map(&:pass_stats).sort_by { |s| -s.rating }} %>

      <table class="stats">
        <thead>
          <tr>
            <th>
            <th>Att</th>
            <th>FGM</th>
            <th>%FG</th>
            <th>Long</th>
            <th>BLK</th>
            <th>1-19</th>
            <th>20-29</th>
            <th>30-39</th>
            <th>40-49</th>
            <th>50+</th>
            <th>XPA</th>
            <th>XPM</th>
            <th>%XP</th>
          </tr>
        </thead>
        <tbody>
          <% @league.total_team_stats.sort_by { |s| -s.kick_stats.fgs_made }.each do |team_stats| -%>
            <% kick_stats = team_stats.kick_stats -%>
            <tr>
              <td><%= team_stats.team %></td>
              <td class="numeric"><%= kick_stats.attempts %></td>
              <td class="numeric"><%= kick_stats.fgs_made %></td>
              <td class="numeric"><%= "%3.1f" % kick_stats.pct_fg %></td>
              <td class="numeric"><%= kick_stats.long %></td>
              <td class="numeric"><%= kick_stats.fgs_blocked %></td>
              <td class="numeric"><%= fgs_made_att_display( 1..19, kick_stats) %></td>
              <td class="numeric"><%= fgs_made_att_display(20..29, kick_stats) %></td>
              <td class="numeric"><%= fgs_made_att_display(30..39, kick_stats) %></td>
              <td class="numeric"><%= fgs_made_att_display(40..49, kick_stats) %></td>
              <td class="numeric"><%= fgs_made_att_display(50..99, kick_stats) %></td>
              <td class="numeric"><%= kick_stats.xps_attempted %></td>
              <td class="numeric"><%= kick_stats.xps_made %></td>
              <td class="numeric"><%= "%3.1f" % kick_stats.pct_xp %></td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>

    <div class="stats_tables">
      <%= render partial: 'team_run_stats',
            locals: {team_run_stats: @league.total_team_stats.map(&:run_defense_stats).sort_by { |s| s.yards }} %>

      <%= render partial: 'team_pass_stats',
            locals: {team_pass_stats: @league.total_team_stats.map(&:pass_defense_stats).sort_by { |s| s.rating }} %>
    </div>

    <div class="stats_tables">
      <%= render partial: 'team_run_stats',
            locals: {team_run_stats: @league.total_team_stats.map(&:kickoff_return_stats).sort_by { |s| -s.yards_per_carry }} %>

      <%= render partial: 'team_run_stats',
            locals: {team_run_stats: @league.total_team_stats.map(&:punt_return_stats).sort_by { |s| -s.yards_per_carry }} %>

      <%= render partial: 'team_run_stats',
            locals: {team_run_stats: @league.total_team_stats.map(&:int_return_stats).sort_by { |s| -s.yards_per_carry }} %>
    </div>
  <% end -%>
</div>