config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'leagues#index'

  resources :teams, only: :index

  resources :games, only: %i[index show update] do
    collection do
      get :replay
    end
  end

  resources :leagues, only: %i[index show]

  resources :schedules, only: %i[] do
    member do
      patch :postpone
    end
  end

  resources :team_traits, only: [] do
    member do
      get :increment, :decrement
    end
  end

  resources :stats, only: :index

  resources :play_sets, only: :index
  resources :off_def_charts, only: :index

  resources :offensive_play_sets, only: %i[create update]
  resources :defensive_play_sets, only: %i[create update]

  resources :miscs, only: :index
end

app/models/game.rb
class Game < ApplicationRecord
  extend GameEnum
  include GameAttributes

  belongs_to :home_team, class_name: 'Team'
  belongs_to :visitors , class_name: 'Team'
  has_many :plays         , dependent: :destroy
  has_many :game_snapshots, through: :plays
  has_one :schedule, dependent: :destroy

  attr_reader   :result, :previous_spot, :announcement, :goes_into_huddle
  attr_accessor :offensive_play, :offensive_play_set,
                :defensive_play, :defensive_play_set,
                :no_huddle, :two_point_try, :error_message

  KICKOFF_YARDLINE = 35
  TOUCHBACK_YARDLINE = 20
  KICKOFF_YARDLINE_AFTER_SAFETY = 20

  def played_over?
    final? && result.blank?
  end

  def ongoing?
    !final? && !(quarter == 1 && time_left == 900)
  end

  def playoff?
    schedule.is_playoff
  end

  def human_assisted?
    offense_human_assisted? || defense_human_assisted?
  end

  # TODO: Implement properly offense_human?() and defense_human?()
  def offense_human?
    offense_human_assisted?
  end
  def defense_human?
    defense_human_assisted? && scrimmage?
  end

  def offense_human_assisted?
    offense.human_assisted?
  end

  def defense_human_assisted?
    defense.human_assisted?
  end

  def choose_offense?
    huddle? && offense_human?
  end

  def choose_defense?
    playing? && defense_human?
  end

  def allows_offensive_play_choice?
    offense_human? || offense_human_assisted?
  end

  def allows_defensive_play_choice?
    defense_human? || defense_human_assisted?
  end

  def hides_offensive_play?
    allows_defensive_play_choice? && offensive_play&.normal? && !result
  end

  def hides_defensive_play?
    allows_offensive_play_choice? && !result
  end

  def shows_offensive_plays_to_choose?
    (huddle? || playing?) && allows_offensive_play_choice?
  end

  def shows_defensive_plays_to_choose?
    playing? && offensive_play&.normal? && allows_defensive_play_choice?
  end

  def offense_hurrying?
    offense.offensive_strategy.hurrying?(self)
  end

  def clock_runs_out?
    end_of_quarter? || end_of_half? || final?
  end

  def for?(team)
    [home_team_id, visitors_id].include?(team.id)
  end

  def head_to_head_for?(teams)
    team_ids = teams.map(&:id)
    team_ids.include?(home_team_id) && team_ids.include?(visitors_id)
  end

  def within_conference?
    home_team.conference && home_team.conference == visitors.conference
  end

  def within_division?
    home_team.division && home_team.division == visitors.division
  end

  def overtime?
    quarter >= 5
  end

  def opponent_for(team)
    return nil unless for?(team)
    team == home_team ? visitors : home_team
  end

  def league
    schedule&.league
  end

  def result_and_scores_for(team)
    return [] unless final? && for?(team)
    score_own, score_opp = score_home, score_visitors
    score_own, score_opp = score_opp, score_own if team == visitors
    r = %w[L T W][(score_own <=> score_opp) + 1]
    [r, score_own, score_opp]
  end

  def score_visitors_by_quarter
    scores_by_quarter_for(home_team: false)
  end

  def score_home_by_quarter
    scores_by_quarter_for(home_team: true)
  end

  def teams
    [home_team, visitors]
  end

  def winner
    return nil unless final?
    return nil if score_home == score_visitors
    score_home > score_visitors ? home_team : visitors
  end

  def loser
    return nil unless final?
    return nil if score_home == score_visitors
    score_home < score_visitors ? home_team : visitors
  end

  def prompt
    "#{status}#{no_huddle ? '(no huddle)' : ''}"
  end

  def default_play_input
    return 'choose offense' if choose_offense?
    return 'choose defense' if choose_defense?
    next_play
  end

  def determine_offensive_play(play_input)
    return if timeout_taken?(play_input) || with_no_huddle?(play_input)
    if play_input == '>' && offense_human_assisted?
      @goes_into_huddle = true
      play_input = 'scrimmage'
    end
    @offensive_play_set = nil

    play_input = case play_input.upcase
                 when 'P'
                   OffensivePlay.normal_punt.number
                 when 'FG'
                   OffensivePlay.field_goal.number
                 when 'XP'
                   OffensivePlay.extra_point.number
                 when 'TWO'
                   OffensivePlay.two_point_conversion.number
                 when 'SPK'
                   OffensivePlay.spike_ball.number
                 when 'LET'
                   OffensivePlay.let_clock_run.number
                 when 'KN', 'KNE', 'KNEE', 'KNEEL'
                   OffensivePlay.kneel_down.number
                 else
                   play_input
                 end

    if offense_human_assisted? || OffensivePlay.find_by(number: play_input.to_i)
      if offense_human_assisted? && StrategyTool.new(self).needs_defense_timeout?
        return if timeout_taken?('TD')
      end

      play = OffensivePlay.find_by(number: play_input.to_i)
      play = OffensivePlay.normal_kickoff if kickoff? && !play&.kickoff?
      if play.nil? && play_input != 'choose offense'
        self.error_message = "Illegal offensive play '#{play_input}'"
      end
      if play&.let_clock_run?
        is_successful = let_clock_run
        if is_successful
          return
        else
          play = nil
          self.error_message = "Cannot let clock run out"
        end
      end
      @offensive_play = play
    elsif !Game.next_plays.keys.include?(play_input)
      self.error_message = "Illegal offensive play '#{play_input}'"
      @offensive_play = nil
    else
      offensive_strategy = offense.offensive_strategy
      @offensive_play, option = offensive_strategy.choose_play(self)
      if @offensive_play&.let_clock_run?
        # FIXME: Do not let let_clock_run() to return false.
        let_clock_run
        return
      end
      return if timeout_taken?(option) || with_no_huddle?(option)
      @offensive_play_set = offensive_strategy.play_set
    end
    self.status = :playing if @offensive_play
    if @offensive_play&.two_point_conversion?
      self.two_point_try = true
      self.ball_on = 98
    end
    save!
    @offensive_play
  end

  def determine_defensive_play
    return if defense_human?
    defensive_strategy = defense.defensive_strategy
    @defensive_play = defensive_strategy.choose_play(self).tap {
      @defensive_play_set = defensive_strategy.play_set
    }
  end

  def remove_announcement
    @announcement = nil
  end

  private

    def let_clock_run
      if !clock_stopped && (time_left <= 40 || ([2, 4].include?(quarter) && time_left > 120 && time_left <= 160))
        advance_clock(40, in_play: false)
        save!
        true
      else
        false
      end
    end

    def timeout_taken?(play_input)
      return false if play_input.blank?
      is_offense = \
        case play_input.upcase.split(/\W/).first
        when 'T'
          defense_human? ? offense_human? : true
        when 'TO'
          true
        when 'TD'
          false
        else
          return false
        end
      return false if timeout_left(is_offense).zero?

      time_left_up_to = nil
      if is_offense && play_input =~ /(\d+)\z/
        time_left_up_to = Integer($1)
      end
      use_timeout(is_offense, time_left_up_to)

      @result = "Timeout ##{3 - timeout_left(is_offense)} by #{is_offense ? 'offense' : 'defense'}"
      return true
    end

    def with_no_huddle?(play_input)
      return false unless play_input&.upcase == 'NH'
      @no_huddle = !@no_huddle unless clock_stopped
      true
    end

    TIME_LEFT_UP_TO_FOR_FG = 2

    def use_timeout(is_offense, time_left_up_to = nil)
      is_home = (home_has_ball && is_offense) || (!home_has_ball && !is_offense)
      is_home ? self.timeout_home -= 1 : self.timeout_visitors -= 1

      if time_left_up_to
        self.time_left = [time_left - (40 - time_left_up_to), TIME_LEFT_UP_TO_FOR_FG].max
      end

      self.clock_stopped = true
      save!
    end

    def play_result_from_chart
      result_chart = offense.play_result_chart
      result_chart.result(@offensive_play, @defensive_play)
    end

    def get_play(value)
      @defensive_play ||= value == 'choose defense' ? nil : DefensivePlay.pick_from(value&.upcase)
      if defense_human? && offensive_play.normal? && !defensive_play
        raise Exceptions::IllegalResultStringError, "Illegal defensive play '#{value}'"
      elsif defensive_play
        @defensive_play_set = nil
      end

      result = \
        if offensive_play&.normal? && (defense_human? || defense_human_assisted? || value.blank?)
          play_result_from_chart
        elsif value.present? && value != 'choose defense'
          unless value.start_with?('=')
            raise Exceptions::IllegalResultStringError, "Specify result string with '=' at head"
          end
          value[1 .. -1]
        end
      Play.parse(result, offensive_play)
    end

  public

  def play(value=nil)
    unless clock_stopped
      @no_huddle = true if offensive_play&.spike_ball?
      time_to_huddle = \
        if last_play_out_of_bounds?
          no_huddle ? rand(2 .. 5) : 30 - rand(0 .. 5)
        else
          (no_huddle ? 10 : 40) - rand(0 .. 5)
        end
      is_two_minute_warning = advance_clock(time_to_huddle, in_play: false)
      return if clock_runs_out? || is_two_minute_warning
    end

    game_snapshot = GameSnapshot.take_snapshot_of(self)

    value = nil if Game.next_plays.keys.include?(value)
    self.error_message = nil
    begin
      @result = get_play(value)
    rescue Exceptions::IllegalResultStringError => e
      self.error_message = e.message
      return
    end

    @previous_spot = ball_on
    self.next_play = :scrimmage
    self.status = :huddle
    if @result.two_point_try?
      @two_point_try = true
      self.ball_on = 98
      return
    end

    @result.change_due_to(self)
    if @result.field_goal_try? || @result.extra_point_try?
      try_field_goal(@result)
    else
      yardage_play(@result)
    end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update]

  def index
    league = League.find_by(id: params[:league_id])
    @games = Game.all.find_all { |g| g.schedule&.league == league }
    @games.sort_by! { |g| g.schedule || g.created_at }
  end

  def show
    if params[:two_point_try] == 'true'
      session[:offensive_play_id] = nil
      @game.two_point_try = true
      @game.ball_on = 98
      @game.huddle!
    else
      offensive_play_id = session[:offensive_play_id]
      @game.offensive_play = OffensivePlay.find(offensive_play_id) if offensive_play_id
      @play_id_to_show_details = params[:play_id_to_show_details].to_i
    end

    @offensive_play_id_in_session = session[:offensive_play_id]
  end

  def update
    @game.no_huddle = (params[:no_huddle] == 'true') || session[:no_huddle]
    @game.two_point_try = (params[:two_point_try] == 'true') || session[:two_point_try]
    @game.ball_on = 98 if @game.two_point_try

    @game_snapshot_prev = nil
    if params[:play] == 'to_final_minutes'
      @game.to_final_minutes!
    elsif params[:play] == 'revert'
      begin
        @game.revert!
      rescue => e
        @game.error_message = e.to_s
      end
    elsif Game.tampering_game?(params[:play])
      @game.tamper(params[:play])
    elsif @game.final?
      if @game.playoff?
        @game.league&.eliminate_loser_in!(@game)
      end
    elsif @game.end_of_quarter? || @game.end_of_half?
      if session[:next_quarter]
        @game.advance_to_next_quarter
        @game.save!
        session[:next_quarter] = nil
      else
        session[:next_quarter] = true
      end
    elsif @game.huddle?
      @game.determine_offensive_play(params[:play]).tap do |play|
        session[:offensive_play_id]     = play&.id
        session[:offensive_play_set_id] = @game.offensive_play_set&.id
        session[:no_huddle] = @game.no_huddle
      end
      @game.determine_defensive_play.tap do |play|
        session[:defensive_play_id]     = play&.id
        session[:defensive_play_set_id] = @game.defensive_play_set&.id
      end
    else
      @game.offensive_play     = OffensivePlay   .find_by(id: session[:offensive_play_id])
      @game.offensive_play_set = OffensivePlaySet.find_by(id: session[:offensive_play_set_id])
      @game.defensive_play     = DefensivePlay   .find_by(id: session[:defensive_play_id])
      @game.defensive_play_set = DefensivePlaySet.find_by(id: session[:defensive_play_set_id])
      if %w[cancel <].include?(params[:play]) || !@game.offensive_play
        @game.cancel_offensive_play
        render :show and return
      elsif params[:play] =~ /\A\d{1,3}\z/ && @game.offense_human_assisted?
        session[:offensive_play_id] = @game.determine_offensive_play(params[:play])&.id
        render :show and return
      elsif params[:play] =~ /\A[a-j]+\z/i && @game.defense_human_assisted?
        begin
          play = DefensivePlay.pick_from(params[:play].upcase)
          @game.defensive_play = play
          @game.defensive_play_set = nil
          session[:defensive_play_id]     = play&.id
          session[:defensive_play_set_id] = nil
        rescue Exceptions::IllegalResultStringError => e
          @game.error_message = e.message
        end
        render :show and return
      end

      @game.play(params[:play])

      if @game.error_message.blank?
        session[:offensive_play_id] = nil
        @game.save!
        @game.no_huddle = false
        session[:no_huddle] = false
      end
      if @game.two_point_try
        redirect_to game_path(@game, two_point_try: true) and return
      elsif @game.result.is_a?(Play)
        game_snapshot_prev = @game.game_snapshots.order(:play_id).last
        @game_snapshot_prev = game_snapshot_prev&.dup
      end
      #game_snapshot_prev.update_scores_by(@game)
    end

    @game.remove_announcement if !@game.human_assisted? && @no_announce
    render :show
  end

  def replay
    play = Play.find(params[:play_id])
    @game_snapshot_prev = play.game_snapshot
    next_play = play.game.plays.where("number > ?", play.number).order(:number).first
    @game = next_play&.game_snapshot || GameSnapshot.take_snapshot_of(play.game).tap { |gss| gss.play = play }
    @game.result = play
    @game.set_plays_and_play_sets_from_result
    @game.announcement = Announcer.announce(play)
    @replay = true
    render :show
  end

  def new
    redirect_to Game.create!
  end

  private

    def set_game
      begin
        @game = Game.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to games_path
      end
    end
end

app/helpers/games_helper.rb
module GamesHelper

  def down_and_yard_display(game)
    if game.end_of_half?
      'HALFTIME'
    elsif game.final?
      'FINAL'
    elsif game.kickoff?
      'KICKOFF'
    elsif game.two_point_try
      'TWO POINT'
    elsif game.extra_point?
      'XP'
    else
      yard = game.goal_to_go? ? 'Goal' : game.yard_to_go
      "#{game.down.ordinalize} & #{yard}"
    end
  end

  def time_left_display(time_left)
    mins = time_left / 60
    format("%d:%02d", mins, time_left - mins * 60)
  end

  def game_time_display(game)
    quarter, time_left = game.quarter, game.time_left
    if quarter == 2 && time_left.zero?
      'Halftime'
    else
      "#{quarter}Q #{time_left_display(time_left)}"
    end
  end

  def live_score_display(game)
    [
      game_time_display(game),
      "#{game.visitors.abbr} #{game.score_visitors} - #{game.home_team.abbr} #{game.score_home}"
    ].join(' ')
  end

  def ball_on_display(game)
    ball_on = game.ball_on
    if game.end_of_half? || game.final?
      nil
    elsif ball_on == 50
      '--- 50'
    elsif ball_on < 50
      "Own #{format('%2d', ball_on)}"
    else
      "Opp #{format('%2d', 100 - ball_on)}"
    end
  end

  def offensive_play_display(game)
    return 'X' * 10 if game.hides_offensive_play?
    play_set = game.offensive_play_set
    play = game.offensive_play
    fg_yard = play&.field_goal? && !game.result ? " #{100 - game.ball_on + 17} yard" : ""
    "#{play}#{fg_yard}#{play_set.blank? ? '' : " : from #{play_set}"}"
  end

  def defensive_play_display(game)
    return nil if (game.huddle? && !game.result) || !game.offensive_play&.normal?
    return 'X' * 10 if game.hides_defensive_play?
    play_set = game.defensive_play_set
    "#{game.defensive_play}#{play_set.blank? ? '' : " : from #{play_set}"}"
  end

  def yards_per_carry_display(stats)
    "%2.1fy" % stats.run_stats.yards_per_carry
  end

  def pct_comp_display(stats)
    "%3.1f%%" % stats.pass_stats.pct_comp
  end

  def long_runs_display(stats)
    "[#{stats.run_stats.longs.sort.reverse.join(' ')}]"
  end

  def long_passes_display(stats)
    "[#{stats.pass_stats.longs.sort.reverse.join(' ')}]"
  end
end

app/views/games/_score_board.html.erb
<% if game -%>
  <tr>
    <td class="tight"><%= game.home_has_ball ? '' : '<>' %>
    <td><%= game.visitors.abbr %></td>
    <% if game.final? -%>
      <% game.score_visitors_by_quarter.each do |score| -%>
        <td class="numeric score_by_quarter"><%= score %></td>
      <% end -%>
    <% end -%>
    <td class="numeric <%= game.final? ? 'score_final' : '' %>">
      <%= game.score_visitors %>
    </td>
    <td><%= '.' * game.timeout_visitors %></td>
    <td><%= "#{game.quarter}Q" %></td>
    <td><%= down_and_yard_display(game) %></td>
  </tr>
  <tr>
    <td class="tight"><%= game.home_has_ball ? '<>' : '' %>
    <td><%= game.home_team.abbr %></td>
    <% if game.final? -%>
      <% game.score_home_by_quarter.each do |score| -%>
        <td class="numeric score_by_quarter"><%= score %></td>
      <% end -%>
    <% end -%>
    <td class="numeric <%= game.final? ? 'score_final' : '' %>">
      <%= game.score_home %>
    </td>
    <td><%= '.' * game.timeout_home %></td>
    <td class="<%= game.clock_stopped ? '' : 'elapsing' %>">
      <%= time_left_display(game.time_left) %>
    </td>
    <td><%= ball_on_display(game) %></td>
  </tr>
<% end -%>

app/views/games/_strategy_tool_judgments.html.erb
<div class="strategy_tool_judgments">
  <table>
    <tbody>
      <tr>
        <td>Offensive play set:</td>
        <td><%= game.offense.offensive_strategy.offensive_play_set(game) %></td>
      </tr>
      <tr>
        <td>Defensive play set:</td>
        <td><%= game.defense.defensive_strategy.defensive_play_set(game) %></td>
      </tr>

      <% StrategyToolJudge.judgments(game).each do |name, value| -%>
        <% is_true = value.is_a?(TrueClass) -%>
        <tr>
          <td class="<%= is_true ? 'true' : '' %>">
            <%= name %>
          </td>
          <td class="<%= is_true ? 'true' : '' %> value">
            <%= is_true              ? 'TRUE'
              : value.is_a?(Numeric) ? time_left_display(value.to_i)
              : value %>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/games/index.html.erb
<div class="games_index">
  <table>
    <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| -%>
        <% stats = Stats::Game.new(game)
           stats_visitors = stats.stats_visitors
           stats_home     = stats.stats_home
        -%>
        <tr>
          <td class="numeric"><%= link_to game.id, game %></td>
          <td><%= game.visitors %></td>
          <td class="numeric score"><%= game.score_visitors %></td>
          <td><%= game.home_team %></td>
          <td class="numeric score"><%= game.score_home %></td>
          <td><%= "#{game.quarter}Q" %></td>
          <td class="numeric"><%= time_left_display(game.time_left) %></td>
          <td><%= "#Play's = #{game.plays.count}" %></td>
          <td><%= link_to 'stats', stats_path(game_id: game) %></td>
          <td><%= "#{yards_per_carry_display(stats_visitors)} vs #{yards_per_carry_display(stats_home)}" %></td>
          <td><%= "#{long_runs_display(stats_visitors)} vs #{long_runs_display(stats_home)}" %></td>
          <td><%= "#{pct_comp_display(stats_visitors)} vs #{pct_comp_display(stats_home)}" %></td>
          <td><%= "#{long_passes_display(stats_visitors)} vs #{long_passes_display(stats_home)}" %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/games/show.html.erb
<table id="score_board" class="score_board" <%= 'hidden' if @game_snapshot_prev %>>
  <%= render partial: 'score_board', locals: {game: @game} %>
</table>
<table id="score_board_prev" class="score_board" <%= 'hidden' unless @game_snapshot_prev %>>
  <%= render partial: 'score_board', locals: {game: @game_snapshot_prev} %>
</table>

<div class="field_vision">
  <% field_vision = FieldVision.instance
     field_vision.real = @real
     field_vision.size_multiplier = @real ? 1.5 : 1.0
     field_vision.place_ball_marker(@game_snapshot_prev || @game) -%>
  <%= field_vision.to_s.html_safe %>
</div>

<br>
<% announcement = @game.announcement
   hidden_due_to_announcement = announcement && !announcement.empty? ? 'hidden' : '' -%>
<div id="announce_board" data-announcements="<%= announcement&.to_s(speed: @speed_of_announce) %>"></div>
<table id="information_board" <%= hidden_due_to_announcement %>>
  <tr>
    <td><%= @game.result %></td>
  </tr>
  <tr>
    <td><%= offensive_play_display(@game) %></td>
  <tr>
  </tr>
    <td><%= defensive_play_display(@game) %></td>
  </tr>
</table>

<% unless @replay -%>
  <div id="form_command" <%= hidden_due_to_announcement %>>
    <br>
    <%= form_tag @game, method: :patch do %>
      <%= @game.prompt %>
      <%= text_field_tag :play, @game.default_play_input, onfocus: "this.select();", autofocus: true %>
      <%= hidden_field_tag :no_huddle, @game.no_huddle %>
      <%= hidden_field_tag :two_point_try, @game.two_point_try %>
      <%= submit_tag :proceed %>

      <%= link_to "Stats", stats_path(game_id: @game) %>
      <%= link_to "Games", games_path(league_id: @game.league) %>
      <%= link_to 'Teams', '#', id: 'toggle_teams' %>
      <% if @game.league -%>
        <%= link_to "League", @game.league %>
      <% end -%>

      <div class="error"><%= @game.error_message %></div>
    <% end -%>
  </div>

  <% unless @game.played_over? -%>
    <div id="judgments_and_plays">
      <div id="strategy_tool_judgments">
        <div style="margin-bottom: 5px;">
          <div><%= "speed = #{@speed_of_announce || 1}" %></div>
          <div>
            <% label = "announce = #{@no_announce ? 'OFF' : 'ON'}" -%>
            <%= link_to label, game_path(@game, no_announce: !@no_announce),
                        id: "toggle_announce", tabindex: -1 %>
          </div>
          <%#= "session[:offensive_play_id] = #{@offensive_play_id_in_session.inspect}" %>
          <%= "@game.two_point_try = #{@game.two_point_try.inspect}" %>
        </div>
        <%= render partial: 'strategy_tool_judgments', locals: {game: @game} %>
      </div>

      <% if @game.shows_offensive_plays_to_choose? -%>
        <% [OffensivePlay.normal_plays, OffensivePlay.non_normal_plays].each do |plays| -%>
          <table class="plays_to_choose">
            <% plays.order(:number).each do |offensive_play| -%>
              <% clazz = ''
                 clazz = 'border_bottom' if offensive_play.number % 4 == 0
                 clazz = 'border_top'    if offensive_play.number % 100 == 1
                 clazz = 'strike'        if offensive_play.name == 'Coffin Corner Punt' -%>
              <tr class="<%= clazz %>">
                <td class="numeric"><%= offensive_play.number %></td>
                <td><%= offensive_play.name %></td>
              </tr>
            <% end -%>
          </table>
        <% end -%>
      <% elsif @game.shows_defensive_plays_to_choose? -%>
        <table class="plays_to_choose">
          <tr class="border_bottom">
            <td>
            <td>
            <td>Against Run</td>
            <td>Against Pass</td>
          </tr>
          <% DefensivePlay.all.each do |defensive_play| -%>
            <tr class="<%= %>">
              <td><%= defensive_play.name %></td>
              <td><%= defensive_play.formation %></td>
              <td><%= defensive_play.against_run %></td>
              <td><%= defensive_play.against_pass %></td>
            </tr>
          <% end -%>
        </table>
      <% end -%>
    <% end -%>

    <div class="team_traits" hidden>
      <%= render partial: 'teams/traits', locals: {teams: [@game.visitors, @game.home_team]} %>
    </div>
  </div>

  <div class="buttons" <%= hidden_due_to_announcement %>>
    <span id="toggle_plays_display" class="button">[Plays]</span>
    <span id="toggle_scorings" class="button">[Scorings]</span>
    <% unless @game.final? -%>
      <span id="toggle_stats_display" class="button">[Stats]</span>
    <% end -%>
  </div>

  <table id="play_by_play" class="table_base" <%= 'hidden' unless @game.played_over? %>>
    <% plays = @game.plays.includes(:game_snapshot).order(number: :desc).tap { |plays|
                 plays.each_cons(2) do |next_play, play|
                   next_play.is_two_point_try = play.touchdown? && !next_play.extra_point_try?
                 end
               } -%>
    <%= render plays %>
  </table>

  <div <%= 'hidden' unless @game.played_over? %>>
    <div class="stats" <%= 'hidden' unless @game.played_over? %>>
      <div>
        <% stats = Stats::Game.new(@game) -%>
        <%= render partial: 'stats/team', locals: {team_stats: stats.stats_visitors} %>
        <%= render partial: 'stats/team', locals: {team_stats: stats.stats_home    } %>
      </div>

      <div>
        <%= render partial: 'teams/traits', locals: {teams: [@game.visitors, @game.home_team]} %>
      </div>
    </div>
  </div>
<% end -%>